### ISSUE TITLE
Seed data

### ISSUE THREAD

**Issue by jlbeard84** [bferguson3/kemcowiki#9]
Might want to add a method to seed some data for each of the different types.

Logic would be like:
```
foreach (item in seedGames)
{
    // check if item id exists in db
    // if not, insert
}
```

And run this either via an api call or on startup.

**Comment by bferguson3** [comment]
You'd have to explain to me a bit more of what seeding is for

**Comment by jlbeard84** [comment]
Yeah the more I think about it the more I think we can just skip this.
